### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by hervegithub** [BuildForSDGCohort2/Team-364-Frontend#10]
Base in this image, create a login page on our app
![login-page](https://user-images.githubusercontent.com/56480426/91508666-10bec200-e8d0-11ea-8e4f-0650d7d11d89.png)

**Comment by Rudy-Menekam** [comment]
can you assign me this issue

**Comment by hervegithub** [comment]
this issue is taken

**Comment by Rudy-Menekam** [comment]
oops okay, how do I know an issue is not taken yet?
